installation:
  - changed-files:
      - any-glob-to-any-file: ["pyproject.toml", "setup.py"]

ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**/*", "codecov.yaml", ".pre-commit-config.yaml", ".ruff.toml", ".style.yapf", "setup.cfg"]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["docs/**/*", "readthedocs.yml", "README.MD"]

benchmark:
  - benchmark/**/*

sampler:
  - pyg_lib/csrc/random/**/*
  - pyg_lib/csrc/sampler/**/*
  - pyg_lib/sampler/**/*

ops:
  - pyg_lib/csrc/ops/**/*
  - pyg_lib/ops/**/*

classes:
  - pyg_lib/csrc/classes/**/*
  - pyg_lib/classes/**/*

utils:
  - pyg_lib/csrc/utils/**/*
