name: Setup

inputs:
  python-version:
    required: false
    default: '3.9'
  torch-version:
    required: false
    default: '2.7.0'
  cuda-version:
    required: false
    default: cpu

runs:
  using: composite

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Free up disk space
      if: ${{ runner.os == 'Linux' }}
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
        tool-cache: true

    - name: Set up Windows developer command prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install CUDA ${{ inputs.cuda-version }}
      if: ${{ inputs.cuda-version != 'cpu' }}
      run: |
        bash ./.github/workflows/cuda/${{ runner.os }}.sh ${{ inputs.cuda-version }}
      shell: bash
