name: Setup

inputs:
  python-version:
    required: false
    default: '3.9'
  torch-version:
    required: false
    default: '2.7.0'
  cuda-version:
    required: false
    default: cpu

runs:
  using: composite

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Windows developer command prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install CUDA ${{ inputs.cuda-version }}
      run: |
        bash ./.github/workflows/cuda/${{ runner.os }}.sh ${{ inputs.cuda-version }}
      shell: bash

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      run: |
        pip install torch==${{ inputs.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ inputs.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
        python -c "import torch; print('CXX11 ABI:', torch.compiled_with_cxx11_abi())"
      shell: bash

    - name: Install additional dependencies
      run: |
        pip install setuptools ninja wheel
      shell: bash
