name: Setup

inputs:
  python-version:
    required: false
    default: '3.9'
  torch-version:
    required: false
    default: '2.6.0'
  cuda-version:
    required: false
    default: cpu
  use-mkl:
    required: false
    default: false

runs:
  using: composite

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Free up disk space
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo rm -rf /usr/share/dotnet
      shell: bash

    - name: Set up Windows developer command prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install CUDA ${{ inputs.cuda-version }}
      if: ${{ inputs.cuda-version != 'cpu' }}
      run: |
        bash ./.github/workflows/cuda/${{ runner.os }}.sh ${{ inputs.cuda-version }}
      shell: bash

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      run: |
        pip install torch==${{ inputs.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ inputs.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
        python -c "import torch; print('CXX11 ABI:', torch.compiled_with_cxx11_abi())"
      shell: bash

    - name: Disable CUDNN
      if: ${{ (inputs.cuda-version != 'cpu') && ((inputs.torch-version == '1.12.0') || (inputs.torch-version == '1.13.0')) }}
      run: |
        Torch_DIR=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`
        sed -i '95,100d' ${Torch_DIR}/Caffe2/Caffe2Config.cmake
        sed -i 's/;caffe2::cudnn-public//g' ${Torch_DIR}/Caffe2/Caffe2Targets.cmake
      shell: bash

    - name: Install MKL and set MKL_VERSION, BLAS_INCLUDE_DIR, MKL_DIR
      if: ${{ inputs.use-mkl }}
      run: |
        MKL_VERSION=`python tools/print_mkl_version.py`
        pip install --no-cache-dir mkl-include==${MKL_VERSION} mkl-static==${MKL_VERSION}

        export BLAS_INCLUDE_DIR=`python -c 'import os;import sysconfig;data=sysconfig.get_path("data");print(f"{data}{os.sep}include")'`
        export MKL_DIR=`python -c 'import os;import sysconfig;data=sysconfig.get_path("data");print(f"{data}{os.sep}lib{os.sep}cmake{os.sep}mkl")'`
        export USE_MKL_BLAS=ON
      shell: bash

    - name: Downgrade GLIBC
      if: ${{ runner.os == 'Linux' }}
      run: |
        sed -i '1s/^/#if defined(__linux__) \&\& defined(__x86_64__)\n__asm__(".symver log,log@GLIBC_2.2.5");\n#endif\n/' third_party/METIS/GKlib/gk_proto.h
        sed -i '1s/^/#if defined(__linux__) \&\& defined(__x86_64__)\n__asm__(".symver pow,pow@GLIBC_2.2.5");\n#endif\n/' third_party/METIS/libmetis/metislib.h
      shell: bash

    - name: Install additional dependencies
      run: |
        pip install setuptools ninja wheel
      shell: bash
