name: Build and Push Docker Image

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - aki/manylinux0
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Add steps to build and push your Docker image here
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: ${{ vars.DOCKERHUB_USERNAME }}/pyg-lib:latest
