name: Build wheels

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - aki/testbuild
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read and flatten matrix.json
        id: set-matrix
        run: |
          if [ -n "$GITHUB_EVENT_NAME" ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            filename=".github/matrix_minimal.json"
          else
            filename=".github/matrix_full.json"
          fi
          matrix=$(jq -c '[.[] | { "torch-version": .["torch-version"], "python-version": .["python-version"][], "cuda-version": .["cuda-version"][] }]' $filename)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "matrix=$matrix"

  build-wheel:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Print matrix
        run: |
          echo "Torch: ${{ matrix.torch-version }}"
          echo "Python: ${{ matrix.python-version }}"
          echo "CUDA: ${{ matrix.cuda-version }}"
