name: Cpp Code Coverage

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:

  import:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        torch-version: [1.11.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          pip install torch==${{ matrix.torch-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Configure
        run: |
          Torch_DIR=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` cmake -S . -B build -DWITH_COV=ON -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: |
          cmake --build build --config Debug
      - name: Test
        run: |
          cd build
          ctest -C Debug --output-on-failure --verbose
          cd ..
      - name: Gcov
        run: |
          pip install gcovr
          gcovr -f pyg_lib/csrc/*.cpp --output cov.txt

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          files: cov.txt
