name: Linting

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  ty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: '3.10'
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install ty pytest
          uv pip install torch --index-url https://download.pytorch.org/whl/cpu
          uv pip install scipy torch-geometric triton

      - name: Check type hints
        run: |
          ty check --output-format github --error all
