name: "Close stale issues and PRs"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"  # Everyday at 0:00am UTC/4:00pm PST
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue had no activity for **2 months**. It will be closed in **2 weeks** unless there is some new activity.'
          stale-issue-label: 'stale'
          exempt-issue-labels: '0 - Priority P0,bug,feature,good first issue'
          stale-pr-message: 'This pull request had no activity for **2 months**. It will be closed in **2 weeks** unless there is some new activity.'
          stale-pr-label: 'stale'
          days-before-stale: 60
          days-before-close: 14
          operations-per-run: 200
